language: node_js
node_js:
  - "8"

before_deploy:
  - ./deploy_s3.sh

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_S3_BUCKET_NAME
  skip_cleanup: true
  region: eu-west-1
  local_dir: deploy
